services:
  mysql:
    container_name: hemsva_mysql
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - mysql_network
  
  phpmyadmin:
    container_name: hemsva_pma
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql_network

  frontend:
    build: ./hemsva_frontend
    container_name: hemsva_frontend
    ports:
      - 5173:5173
    volumes:
    - ./hemsva_api:/var/www/html
    - ./hemsva_api/vendor:/var/www/html/vendor
    - ./hemsva_api/node_modules:/var/www/html/node_modules

  api:
    build: ./hemsva_api
    container_name: hemsva_api
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - ./hemsva_api:/var/www/html
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      APP_ENV: local
      APP_DEBUG: 'true'
    networks:
      - mysql_network
networks:
  mysql_network: